Subtract From Selection
aras-p/UnityGaussianSplatting pull request #70
Opened 2023-11-08 05:36 UTC by Waffle1434

Fixes #69 😎
Hold `Ctrl` to subtract from the current selection. Uses `InterlockedAnd`.

2023-11-08 09:09 UTC, aras-p requested changes
One stray debug log, but otherwise looks great!

2023-11-08 09:09 UTC, aras-p commented on package/Runtime/GaussianSplatRenderer.cs
> +            Debug.Log(Input.GetKey(KeyCode.LeftControl));
Stray debug log

2023-11-08 17:44 UTC, JasonDeacutis commented on package/Runtime/GaussianSplatRenderer.cs
> +            Debug.Log(Input.GetKey(KeyCode.LeftControl));
*Shakes fist*

2023-11-08 17:50 UTC, Waffle1434 commented on package/Runtime/GaussianSplatRenderer.cs
> +            Debug.Log(Input.GetKey(KeyCode.LeftControl));
*Shakes fist*
Force pushed

2023-11-09 08:16 UTC, aras-p approved these changes

2023-11-09 08:17 UTC, merged